### ISSUE TITLE
Proposal for 2023 instance of Rookie Draft

### ISSUE THREAD

**Issue by fffrontoffice** [fffrontoffice/rules#87]
**Background**
Rookie draft is currently held live, before the Auction portion. Now that we are on Sleeper, we run rookie draft and auction draft through the app which simplifies team management. However, after the rookie draft, time has to be spent to set up the new draft with the right settings and available auction dollars for each team. This has been time consuming and error prone.

The 2023 draft has a tighter draft window than years past, removing complexity from the morning draft would help us get through the Auction portion without an issue.  

**Proposal**
Only for this year (2023), run the Rookie portion of the draft in the days leading up to the auction draft. We can consider whether or not this is worth doing again for future drafts if we like it.

As a starting point:
* Open draft the Sunday before the draft (or 6 days before).
* Allow 12 hours for a pick to be made
* Wrap up rookie draft by Roster Lock (2 midnights before draft)
* Timeline for getting Practice Squad down to 4 players should remain the same (sometime after the auction).

👍  **Benefits**
* Simplifies set up of Auction Draft settings and team available auction dollars. Avoids errors, lets us jump right into it knowing we have it set up right.
* Allows for more time to research and select your rookie picks.  

👎  **Drawbacks**
* Live commentary on picks goes from in-person to slack.
* Unclear what should happens if someone misses their 12 hour window. Auto-draft should not really apply.
* Unclear what should happen if we don't wrap up by Roster Lock. Really no reason why it should take that long, but technically could leave a couple picks left while an owner sits on their pick too long.

**Comment by willy4short** [comment]
The draft, both rookie and FA auction, is one of my favorite weekends of the year.  I'm not necessarily a fan of diluting the process so to speak, however I do understand the time sensitive nature of this year and certainly the tech issues that will inevitably arise.  Since this weekend has evolved into what it has become, why don't we carve out some time on one of the evenings before the morning of the FA auction draft?  Friday early evening rookie draft, late evening shenanigans, Saturday morning FA auction? 

**OFFICIAL VOTE:** - Vote in favor of moving the rookie draft to the days leading up to the FA auction draft.  Would prefer to all do it in person, but am willing to switch to the week leading up as proposed above.

**Comment by ClubAtletico** [comment]
I won't get there until late Friday night, so if we're not going to do it the morning of, I would prefer doing it via slack/sleeper.

**Comment by jsmunro24** [comment]
I'm all in for a "slow" online rookie draft. While exciting in person, the auction draft is the main event and we could easily shave off 30 mins by doing the rookie draft throughout this week. Rushing through the auction draft on Saturday to make it to golf course isnt awesome for anybody.
